#!/usr/bin/env bash

set -e # Exit on error

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"

CONFIG="install.conf.yaml"

DOTBOT_DIR="submodules/dotbot"
DOTBOT_BIN="bin/dotbot"

# Update dotbot
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

# Run dotbot
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
