# ! bash_profile is read by login shells, bashrc is read by non-login shells
# ! Keep in here login/environment specific settings

case "$(uname -s)" in
  Darwin) source "$HOME/dotfiles/configs/bash/macos.bash_profile" ;;
  Linux) source "$HOME/dotfiles/configs/bash/linux.bash_profile" ;;
esac

# Load interactive config
[ -r "$HOME/.bashrc" ] && source $HOME/.bashrc