# ! bash_profile is read by login shells, bashrc is read by non-login shells
# ! Keep in here login/environment specific settings

# Set up Homebrew env on macOS
if [[ "$(uname -s)" == "Darwin" ]]; then
    # %% Locale issues in macOS Terminal.app bash
    # %% -------------------------------------------------------------------------------
    # * Run `locale` to see the current locale settings.

    # Without this locale setting brew-installed bash complains:
    # `-bash: warning: setlocale: LC_COLLATE: cannot change locale (): No such file or directory`
    # ! It is a Terminal.app only issue when I tested it on macOS 13.7.8 in
    # ! Terminal.app Version 2.13 (447.1). iTerm2 Build 3.6.6 does not have this issue at all.
    # * This will propagate to all the other `locale` variables if not set explicitly.
    export LANG="en_US.UTF-8"

    # Setting LANG as above also sets LC_CTYPE to the same value LC_CTYPE="en_US.UTF-8" but
    # bash does not like it and prints:
    # `-bash: warning: setlocale: LC_CTYPE: cannot change locale (): Bad file descriptor`
    # The "Set locale environment variables on startup" option in Terminal.app
    # sets LC_CTYPE to "UTF-8" which solves the error message in Terminal.app.
    # However this is not the standard on many Linux systems.
    # Commented out since I switched to iTerm2.
    # export LC_CTYPE="UTF-8"
    # %% -------------------------------------------------------------------------------
    
    # Silence bash deprecation warnings on macOS
    export BASH_SILENCE_DEPRECATION_WARNING=1

    if [[ -x /opt/homebrew/bin/brew ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi
fi

# Load interactive config
[[ -r ~/.bashrc ]] && source ~/.bashrc