# -l: long listing
# -A: list all files, but do not list . and ..
# -h: human readable sizes
# -F: append a character to the end of each file name to indicate its type
alias l="ls -lAhF"

# Don't shoot yourself in the foot
alias rm="rm -i -v"
alias cp="cp -i -v"
alias mv="mv -i -v"

alias code="codium"
alias c="code"
alias o="conda deactivate"